W7D3/goal_setter_app/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :users, only: [:show, :new, :create]

  resource :session, only: [:new, :create, :destroy]
  
end

W7D3/goal_setter_app/app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :bigint           not null, primary key
#  password_digest :string           not null
#  session_token   :string           not null
#  username        :string           not null
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#
# Indexes
#
#  index_users_on_session_token  (session_token) UNIQUE
#  index_users_on_username       (username) UNIQUE
#

class User < ApplicationRecord
  validates :username, :password_digest, :session_token, presence: true
  validates :username, :session_token, uniqueness: true
  validates :password, length: {minimum: 6, allow_nil: true}

  before_validation :ensure_session_token

  def self.find_by_credentials(username, password)
    user = User.find_by(username: username)
    return nil unless user

    user.is_password?(password) ? user : nil
  end

  attr_reader :password

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def is_password?(password)
    BCrypt::Password.new(self.password_digest) == password
  end

  def ensure_session_token
    self.session_token ||= SecureRandom.urlsafe_base64
  end

  def reset_session_token!
    self.session_token = SecureRandom.urlsafe_base64
    self.save!
    self.session_token
  end

end

W7D3/goal_setter_app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user, :logged_in?

  def current_user
    @current_user ||= User.find_by(session_token: session[:session_token])
    return nil unless @current_user
    @current_user
  end

  def require_login
    redirect_to new_session_url unless logged_in?
  end
  
  def logged_in?
    !!current_user
  end

  def login!(user)
    session[:session_token] = user.reset_session_token!
    @current_user = user
  end

  def logout!
    current_user.reset_session_token!
    @current_user = nil
    session[:session_token] = nil
  end

end

W7D3/goal_setter_app/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    render :new
  end

  def create
    user = User.find_by_credentials(params[:user][:username], params[:user][:password])
    
    if user
      login!(user)
      redirect_to user_url(user)
    else
      flash[:errors] = ['Invalid Credentials']
      redirect_to new_session_url
    end
  end

  def destroy
    logout!
    redirect_to new_session_url
  end
end

W7D3/goal_setter_app/app/controllers/users_controller.rb
class UsersController < ApplicationController

  ### created show method to use for redirect controller tests
  def show
    @user = User.find_by(id: params[:id])
    render :show
  end

  def new
    @user = User.new
    render :new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      login!(@user)
      redirect_to user_url(@user)
    else
      flash.now[:errors] = @user.errors.full_messages
      render :new
    end
  end

  private
  def user_params
    params.require(:user).permit(:username, :password)
  end

end

W7D3/goal_setter_app/app/helpers/application_helper.rb
module ApplicationHelper
  def auth_token
    "<input type='hidden'
            name='authenticity_token'
            value='form_authenticity_token'>".html_safe
  end
end

W7D3/goal_setter_app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GoalSetterApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <header>
      <% if logged_in? %>
        <h1>Hello, <%= current_user.username.capitalize %></h1>

        <div>
          <form action="<%= session_url %>" method="POST">
            <input type="hidden" name="_method" value="DELETE">
            <%= auth_token %>
            <input type="submit" value="LOG OUT">        
          </form>
        </div>
      <% else %>
        <div>
          <form action="<%= new_user_url %>" method="GET">
            <%= auth_token %>
            <input type="submit" value="SIGN UP">        
          </form>
          <form action="<%= new_session_url %>" method="GET">
            <%= auth_token %>
            <input type="submit" value="LOG IN">        
          </form>
        </div>
      <% end %>
    </header>

    <div>
      <% if flash[:errors] %>
        <ul>
          <% flash[:errors].each do |error| %>
          <li><%= error %></li>
          <% end %>
        </ul>
      <% end %>
    </div>

    <%= yield %>
  </body>
</html>

W7D3/goal_setter_app/app/views/users/new.html.erb
<h1>Sign Up</h1>

<form action="<%= users_url %>" method="POST">
  <label>Username:
    <input type="text" name="user[username]" value="<%= @user.username %>" id="username">
  </label>

  <label>Password:
    <input type="password" name="user[password]" value="<%= @user.password %>" id="password">
  </label> 

  <%= auth_token %>
  <input type="submit" value="Create User">
</form>

W7D3/goal_setter_app/app/views/users/show.html.erb
<h1>Homepage</h1>
<h3><%= @user.username %></h3>